version: '3'

services:
  # Airflow cluster
  redis:
    image: redis:latest
    container_name: redis
    networks:
      shopee_net:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      shopee_net:
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
          
  airflow-webserver:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow-webserver
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "8282:8080"
    restart: always
    networks:
      shopee_net:
    volumes:
      - airflow_dags:/usr/local/airflow/dags
    command: webserver

  airflow-scheduler:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    restart: always
    networks:
      shopee_net:
    volumes:
      - airflow_dags:/usr/local/airflow/dags      
    command: scheduler

  airflow-worker:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow-worker
    depends_on:
      - airflow-scheduler
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    restart: always
    networks:
      shopee_net:
    volumes:
      - airflow_dags:/usr/local/airflow/dags
    command: worker

  # Spark - Iceberg
  spark-iceberg:
    image: tabulario/spark-iceberg
    build: spark/
    container_name: spark-iceberg
    depends_on:
      - rest
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
    networks:
      shopee_net:
    volumes:
      - iceberg_warehouse:/home/iceberg/warehouse
      - iceberg_notebooks:/home/iceberg/notebooks/notebooks

  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
    ports:
      - 8181:8181
    networks:
      shopee_net:

  # Minio cluster
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    networks:
      shopee_net:
        aliases:
          - warehouse.minio
    volumes:
      - data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    networks:
      shopee_net:
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "

networks:
  shopee_net:

volumes:
  postgres_data:
  airflow_dags:
  iceberg_warehouse:
  iceberg_notebooks:
  data: